ALTER TABLE users ADD COLUMN profile_picture VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN full_name VARCHAR(100) DEFAULT NULL;
ALTER TABLE users ADD COLUMN bio TEXT DEFAULT NULL;
ALTER TABLE users
DROP COLUMN mobile_phone,
DROP COLUMN voip_line,
DROP COLUMN phone; 